#bitbucket-pipelines.yml
image: node:12.8.0

pipelines:
  default:
    - step:
        caches:
          - node
        name: Build React Project
        script:
          - unset CI 
          - npm install
          - npm run-script build
        artifacts:
          - build/**
    - step:
        name: Deploy to Deployment
        trigger: manual
        deployment: staging
        script:
          - echo "Deploying to deployment environment"
          - pipe: atlassian/rsync-deploy:0.3.2
            variables:
              USER: $SSH_USER
              SERVER: $SERVER
              REMOTE_PATH: $REMOTE_PATH_DEV
              LOCAL_PATH: 'build/'
    - step:
        name: Deploy to Production
        trigger: manual
        deployment: production
        script:
          - echo "Deploying to production environment"
          - pipe: atlassian/rsync-deploy:0.3.2
            variables:
              USER: $SSH_USER
              SERVER: $SERVER
              REMOTE_PATH: $REMOTE_PATH_PROD
              LOCAL_PATH: 'build/'
          